version: '3'

services:
  zookeeper:
    image: 'zookeeper:3.7.0'
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crypto
    ports:
      - '5432:5432'

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - '8080:8080'
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/crypto
      - AIRFLOW__CORE__FERNET_KEY='EPQSEvFWiwfcQoHMAGiYnr8Yd1vsj29gSeTcd4JcH10='
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: webserver

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/crypto
      - AIRFLOW__CORE__FERNET_KEY='EPQSEvFWiwfcQoHMAGiYnr8Yd1vsj29gSeTcd4JcH10='
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: scheduler